version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
    allow:
      - dependency-name: "@nilfoundation/hardhat-plugin",
      - dependency-name: "@nilfoundation/niljs"